name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: task
            asset_name: task-linux-amd64.tar.gz
          - os: windows-latest
            artifact_name: task.exe
            asset_name: task-windows-amd64.zip
          - os: macos-latest
            artifact_name: task
            asset_name: task-macos-amd64.tar.gz

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Package (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/release
          tar czf ../../${{ matrix.asset_name }} ${{ matrix.artifact_name }}

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/release
          7z a -tzip ../../${{ matrix.asset_name }} ${{ matrix.artifact_name }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
