name: Release

on:
  push:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch: # For testing without creating a release

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: task
            asset_name: task-linux-x86_64.tar.gz
          - os: windows-latest
            artifact_name: task.exe
            asset_name: task-windows-x86_64.zip
          - os: macos-latest
            artifact_name: task
            asset_name: task-macos-x86_64.tar.gz

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Package (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: tar -czf ${{ matrix.asset_name }} -C target/release ${{ matrix.artifact_name }}

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path "target\release\${{ matrix.artifact_name }}" -DestinationPath "${{ matrix.asset_name }}"
        shell: pwsh

      - name: Upload Release Asset (manually created release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}

      - name: Upload Release Asset (auto-created release)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream
